//! MicroDuck reference-velocity task consumption protocol. No Pastey authority objects.
use serde::{Deserialize, Serialize};
pub const PROTOCOL: &str = "microduck-task-v1";
pub const PROFILE: &str = "reference-velocity-v1";
pub const MAX_LEASE_US: u64 = 3_000_000;
pub const MAX_ACTION_US: u64 = 1_000_000;
pub const REFRESH_LOSS_US: u64 = 200_000;
/// Exact Pastey native reference, 0.03 m/s above the pinned 0.05 stand threshold.
/// With alpha=0.2 at 50 Hz, EMA from zero crosses on tick 5 (100 ms).
/// The one-second ideal command integral is ~0.0736 m, inside 0.01..=0.1 m;
/// measured motion and settling must independently pass qualification.
pub const REFERENCE_FORWARD_MPS: f64 = 0.08;
pub const REFERENCE_TWIST: [f64; 3] = [REFERENCE_FORWARD_MPS, 0.0, 0.0];

/// Trusted isolated launcher facts, not command parameters. Controller identity
/// is generated by robotd and cannot be supplied by the launcher/client.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LaunchIdentity {
    pub environment: String,
    pub domain: String,
    pub body: String,
    pub body_ref: String,
    pub world: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Identity {
    pub environment: String,
    pub domain: String,
    pub body: String,
    pub body_ref: String,
    pub world: String,
    pub controller: String,
}
impl Identity {
    pub fn validate(&self) -> bool {
        [
            &self.environment,
            &self.domain,
            &self.body,
            &self.body_ref,
            &self.world,
            &self.controller,
        ]
        .iter()
        .all(|v| bounded(v))
    }
}
pub fn bounded(v: &str) -> bool {
    !v.is_empty() && v.len() <= 160 && v.bytes().all(|b| b.is_ascii_graphic())
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Install {
    pub protocol: String,
    pub profile: String,
    pub identity: Identity,
    pub domain: String,
    pub session: String,
    pub epoch: u64,
    pub request: String,
    /// Absolute CLOCK_MONOTONIC microseconds, never extended by retry/refresh.
    pub lease_deadline_us: u64,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Action {
    pub install: Install,
    pub action: String,
    pub payload_digest: String,
    pub deadline_us: u64,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Move {
    pub action: Action,
    pub request: String,
    pub sequence: u64,
    /// Native task mode accepts only REFERENCE_TWIST, including on refresh.
    pub twist: [f64; 3],
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Fence {
    pub install: Install,
    /// Pastey advances the domain epoch before sending this request.
    pub next_epoch: u64,
    pub request: String,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Request {
    Status { protocol: String },
    Install { descriptor: Install },
    Admit { descriptor: Action },
    Move { descriptor: Move },
    Fence { descriptor: Fence },
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Receipt {
    pub protocol: String,
    pub profile: String,
    pub identity: Identity,
    pub native_us: u64,
    pub request: String,
    pub accepted: bool,
    pub reason: String,
    pub installed: Option<Install>,
    pub action: Option<Action>,
    pub sequence: u64,
    pub high_water_epoch: u64,
    pub fenced: bool,
    /// Last controller consumption boundary, independent of receipt/physical rest.
    pub consumed_sequence: u64,
}
